
name: React App Deploy to Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    name: Deploying to Surge
    steps:
      - uses: actions/checkout@v2
        
      - name: install Node.js
        uses: actions/setup-node@v2-beta
        with: 
          node-version: 12  
    
      - name: Prepare for yarn installation
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      
      - name: Build React App
        run: npm install --global Surge
      
      - name: Deploy to Surge
        run: surge ./build react-check-app.surge.sh --token{{ secrets.SURGE_TOKEN }}
     
